start =
  grammatical*

grammatical =
  check
  /until
  /spacedCommand

check =
  "check" space* "(" spacedExpr ")" space* "yes:"y:spacedCommand "no:"n:spacedCommand space*
  { return ["check", y, n]; }

until =
   "until" spacedExpr spacedCommand

spacedExpr =
  space* e:expr space*
  { return e; }

expr =
  "true"
  /"false"

spacedCommand =
  space* c:command space*
  { return c; }

space =
  " " / "\n" / "\t"

command =
  "move" / "left" / "right" / "fire" / "idle"